version: '3'
services:

  #PHP Service
  www:
    image: nginx:1.13-alpine
    container_name: www
    ports:
      - "10080:80"
    volumes:
      - ".:/www"
      - "./.docker/nginx.config:/etc/nginx/conf.d/default.conf"
    networks:
      - app-network

  php:
    image: php7.2-mysql
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: php
    volumes:
      - ".:/www"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "10006:3306"
    environment:
      MYSQL_DATABASE: c24app
      MYSQL_ROOT_PASSWORD: c24Secure123!
      MYSQL_USER: c24user
      MYSQL_PASSWORD: c24Secure123!
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: pma
    ports:
      - '10081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: c24Secure123!
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge